spring:
   security:
    oauth2:
      client:
        registration:
          google:
            client-id: 754638558669-62q5oo3a2topoc82t3ijqnnfgvc55e65.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
