name: Build Image And Deploy
on:
    push: 
        branches: 
            - main
        paths:
            - src/**
    workflow_dispatch: 

jobs:
    build-image:
        name: Build Docker Image
        runs-on: ubuntu-latest
        env:
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Docker Login
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_TOKEN}}
            - name: Build Image And Push Image To Docker Hub
              run: docker compose build cleaning-hub && docker compose push cleaning-hub

    deploy-api:
        name: Deploy Docker Image
        runs-on: arisa-server
        needs: [build-image]
        env:
            DB_HOST: ${{secrets.DB_HOST}}
            DB_PORT: ${{secrets.DB_PORT}}
            DB: ${{secrets.DB}}
            DB_USERNAME: ${{secrets.DB_USERNAME}}
            DB_PASSWORD: ${{secrets.DB_PASSWORD}}
            JWT_SEC_KEY: ${{secrets.JWT_SEC_KEY}}
            EMAIL_SERVER_USERNAME: ${{secrets.EMAIL_SERVER_USERNAME}}
            EMAIL_SERVER_PASSWORD: ${{secrets.EMAIL_SERVER_PASSWORD}}
            FE_ACTIVITION_URL: ${{secrets.FE_ACTIVITION_URL}}
            PAYOS_CLIENT_ID: ${{secrets.PAYOS_CLIENT_ID}}
            PAYOS_API_KEY: ${{secrets.PAYOS_API_KEY}}
            PAYOS_CHECKSUM_KEY: ${{secrets.PAYOS_CHECKSUM_KEY}}
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Docker Login
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_TOKEN}}
            - name: Clean Container
              run: docker compose -f docker-compose.prod.yaml -p cleaning-hub-application down cleaning-hub --rmi all -v
              continue-on-error: true
            - name: Pull Images
              run: docker compose -f docker-compose.prod.yaml pull cleaning-hub
            - name: Deploy API
              run: docker compose -f docker-compose.prod.yaml -p cleaning-hub-application up cleaning-hub -d
